# Generated by Django 6.0.4 on 2026-05-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_is_flagged_portfolioview_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='file_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='original_filename',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
