from django.urls import path
from . import views

urlpatterns = [
    path('auth/register/', views.register),
    path('auth/login/', views.login),
    path('auth/refresh/', views.token_refresh),
    path('auth/me/', views.me),
    path('auth/me/update/', views.update_me),
    path('profile/', views.profile),
    path('profile/<int:user_id>/', views.public_profile),
    path('profile/<int:user_id>/view/', views.increment_portfolio_view),
    path('projects/', views.projects),
    path('projects/<int:pk>/', views.project_detail),
    path('projects/<int:pk>/views/', views.increment_project_views),
    path('projects/<int:pk>/like/', views.toggle_like),
    path('projects/<int:pk>/comments/', views.comments),
    path('discover/', views.discover),
    path('discover/top/', views.top_projects),
    path('portfolio/', views.portfolio_design),
    path('stats/', views.student_stats),
    path('templates/', views.templates),
    path('templates/create/', views.create_template),
    path('templates/trashed/', views.trashed_templates),
    path('templates/<int:pk>/', views.template_detail),
    path('announcements/', views.announcements),
    path('categories/', views.categories),
    path('categories/<int:pk>/', views.category_detail),
    path('content/', views.site_content),
    path('admin/stats/', views.admin_stats),
    path('admin/users/', views.admin_users),
    path('admin/users/create/', views.admin_create_user),
    path('admin/users/<int:pk>/', views.admin_update_user),
    path('admin/users/<int:pk>/suspend/', views.toggle_suspend),
    path('notifications/', views.notifications),
    path('notifications/read/', views.mark_notifications_read),
    path('moderation/flagged/', views.flagged_content),
    path('moderation/resolve/<int:pk>/', views.resolve_flag),
]